### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by ShanSabri** [ManuSetty/wishbone#13]
Please see log below: 

```
shans-mbp:wishbone shansabri$ pwd
/Users/shansabri/Downloads/wishbone
shans-mbp:wishbone shansabri$ ls -lthr
total 56
drwxr-xr-x  6 shansabri  staff   204B Jun 16 12:45 tools
drwxr-xr-x  3 shansabri  staff   102B Jun 16 12:45 src
-rw-r--r--  1 shansabri  staff   1.7K Jun 16 12:45 setup.py
drwxr-xr-x  4 shansabri  staff   136B Jun 16 12:45 notebooks
drwxr-xr-x  3 shansabri  staff   102B Jun 16 12:45 docs
drwxr-xr-x  5 shansabri  staff   170B Jun 16 12:45 data
-rw-r--r--  1 shansabri  staff   2.2K Jun 16 12:45 README.md
-rw-r--r--  1 shansabri  staff    18K Jun 16 12:45 LICENSE
shans-mbp:wishbone shansabri$ wishbone_gui.py 
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/wishbone_gui.py", line 463
    if platform.system() == 'Darwin':
                                    ^
TabError: inconsistent use of tabs and spaces in indentation
shans-mbp:wishbone shansabri$ python3 src/wishbone/wishbone_gui.py 
  File "src/wishbone/wishbone_gui.py", line 463
    if platform.system() == 'Darwin':
                                    ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by ShanSabri** [comment]
Same error appears when importing directly from Python: 

```
shans-mbp:wishbone shansabri$ python3 
Python 3.4.1 (v3.4.1:c0e311e010fc, May 18 2014, 00:54:21) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import wishbone
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/wishbone/__init__.py", line 3, in <module>
    from . import wishbone_gui
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/wishbone/wishbone_gui.py", line 463
    if platform.system() == 'Darwin':
                                    ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by ShanSabri** [comment]
Solution: I manually modified the `launch()` method to have consisted tabs/spaces.

**Comment by ManuSetty** [comment]
Thanks for pointing this out. It was has been fixed now.
