### ISSUE TITLE
Error loading FCS data with GUI

### ISSUE THREAD

**Issue by peterch405** [ManuSetty/wishbone#22]
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/chovanec/anaconda3/lib/python3.5/tkinter/__init__.py", line 1549, in __call__
    return self.func(*args)
  File "/home/chovanec/anaconda3/lib/python3.5/site-packages/wishbone-0.3-py3.5.egg/EGG-INFO/scripts/wishbone_gui.py", line 104, in processData
  File "/home/chovanec/anaconda3/lib/python3.5/site-packages/wishbone-0.3-py3.5.egg/wishbone/wb.py", line 244, in from_csv
    df = pd.DataFrame.from_csv( counts_csv_file )
  File "/home/chovanec/anaconda3/lib/python3.5/site-packages/pandas/core/frame.py", line 1189, in from_csv
    infer_datetime_format=infer_datetime_format)
  File "/home/chovanec/anaconda3/lib/python3.5/site-packages/pandas/io/parsers.py", line 562, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/chovanec/anaconda3/lib/python3.5/site-packages/pandas/io/parsers.py", line 315, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/chovanec/anaconda3/lib/python3.5/site-packages/pandas/io/parsers.py", line 645, in __init__
    self._make_engine(self.engine)
  File "/home/chovanec/anaconda3/lib/python3.5/site-packages/pandas/io/parsers.py", line 799, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/chovanec/anaconda3/lib/python3.5/site-packages/pandas/io/parsers.py", line 1213, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 520, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:5129)
  File "pandas/parser.pyx", line 699, in pandas.parser.TextReader._get_header (pandas/parser.c:7634)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 206: invalid start byte
```

Running on Ubuntu 14.04, trying to load sample data. 

Loading the csv files works. It just seems to have problems with fcs. 
When not using the GUI, loading work fine. Any ideas? Thank you.

**Comment by ManuSetty** [comment]
Sorry, FCS files and generally mass cytometry analyses are currently not supported in the GUI. I will leave this open and update it once we add in the functionality.

**Comment by ManuSetty** [comment]
This functionality has been added to the [develop](https://github.com/manusetty/wishbone/tree/develop) branch and will be part of the next release.

**Comment by ManuSetty** [comment]
This is part of version [0.4](https://github.com/ManuSetty/wishbone/releases/tag/0.4)
