### ISSUE TITLE
ValueError: Buffer dtype mismatch, expected 'float64_t' but got 'float'

### ISSUE THREAD

**Issue by mchill2** [ManuSetty/wishbone#30]
Trying to run TSNE on my single-cell RNA-seq .csv and get this error every time. I have reformatted the csv to match the example data set as much as possible. However, I still get this error returned. Information regarding formatting of csv, cell naming conventions, etc. would be most appreciated. 

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/Mchill/anaconda3/envs/snowflake/lib/python3.5/tkinter/__init__.py", line 1550, in __call__
    return self.func(*args)
  File "/Users/Mchill/anaconda3/envs/snowflake/lib/python3.5/site-packages/wishbone-0.4-py3.5.egg/EGG-INFO/scripts/wishbone_gui.py", line 259, in _runTSNE
  File "/Users/Mchill/anaconda3/envs/snowflake/lib/python3.5/site-packages/wishbone-0.4-py3.5.egg/wishbone/wb.py", line 418, in run_tsne
    self.tsne = pd.DataFrame(bh_sne(data, perplexity=perplexity),
  File "/Users/Mchill/anaconda3/envs/snowflake/lib/python3.5/site-packages/tsne-0.1.3-py3.5-macosx-10.6-x86_64.egg/tsne/__init__.py", line 42, in bh_sne
    Y = tsne.run(X, N, X.shape[1], d, perplexity, theta)
  File "tsne/bh_sne.pyx", line 23, in bh_sne.BH_SNE.run (tsne/bh_sne.cpp:1580)
ValueError: Buffer dtype mismatch, expected 'float64_t' but got 'float'
```

Take care

**Comment by ManuSetty** [comment]
Hello

This has been fixed in the develop branch and will be part of the next release. Please update your installation to the develop branch and let us know if face more issues.


```
git clone git://github.com/manusetty/wishbone.git
cd wishbone
git checkout develop
git pull origin develop
sudo pip3 install .

```
