### ISSUE TITLE
wishbone_gui.py error

### ISSUE THREAD

**Issue by thomaslayton** [ManuSetty/wishbone#54]
Hi Manu,

I am having problem using wishbone through the gui. After installation, on attempting to launch the gui I get the following error;

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/wishbone_gui.py", line 4, in <module>
    __import__('pkg_resources').run_script('wishbone==0.4.2', 'wishbone_gui.py')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3017, in <module>
    @_call_aside
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 659, in _build_master
    ws.require(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Cython' distribution was not found and is required by wishbone

I have been using MAGIC through the gui on the same system (mac OS) without any problem so any advice would be much appreciated.

**Comment by ManuSetty** [comment]
Hello

This looks like an issue with missing Cython. Can you please install Cython using `pip3 install Cython` and try again.

**Comment by thomaslayton** [comment]
Thanks! sorry for such a simple question.

I had to install some other dependencies manually but after that the gui launches without any problems.

**Comment by ManuSetty** [comment]
Not a bother - Glad it worked !
