### ISSUE TITLE
Error using Wishbone

### ISSUE THREAD

**Issue by cap76** [ManuSetty/wishbone#57]
Hi, I'm having some trouble getting this to run in either command line or gui. It seems to fail at the last stage, although it seems to run fine in both with the demo data. Example: I get the following errors if I try with attached dataset using wb.run_wishbone(start_cell='Cell_1', components_list=[1, 2, 3], num_waypoints=50)

Building lNN graph...
lNN computed in : 0.00 seconds
Determining waypoints if not specified...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/wishbone/wb.py", line 1068, in run_wishbone
    s=s, k=k, l=k, num_waypoints=num_waypoints, branch=branch)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/wishbone/core.py", line 49, in wishbone
    traj, dist, iter_l, paths_l2l = _trajectory_landmarks( klnn, data, [s], num_waypoints, partial_order, verbose, metric, flock_waypoints, band_sample, branch)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/wishbone/core.py", line 230, in _trajectory_landmarks
    to_replace = np.random.randint(len(waypoints)-1, size=tailk)
  File "mtrand.pyx", line 990, in mtrand.RandomState.randint
  File "mtrand.pyx", line 991, in mtrand.RandomState.randint
  File "randint_helpers.pxi", line 253, in mtrand._rand_int64
TypeError: 'numpy.float64' object cannot be interpreted as an integer

If I try to run wishbone in GUI it runs fine on the pre-processing steps but I get an error when using the wishbone call. Don't think it is a formatting issue. Maybe some property of the dataset?

Using cell gate:
Gate 1
Cell_18
Building lNN graph...
lNN computed in : 0.00 seconds
Determining waypoints if not specified...
Determining shortest path distances and perspectives....
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tkinter/__init__.py", line 1549, in __call__
    return self.func(*args)
  File "wishbone_gui.py", line 360, in _runWishbone
    self.wb.run_wishbone(start_cell=start_cell, k=self.k.get(), components_list=[int(comp) for comp in self.compList.get().split(',')], num_waypoints=self.numWaypoints.get())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/wishbone/wb.py", line 1068, in run_wishbone
    s=s, k=k, l=k, num_waypoints=num_waypoints, branch=branch)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/wishbone/core.py", line 49, in wishbone
    traj, dist, iter_l, paths_l2l = _trajectory_landmarks( klnn, data, [s], num_waypoints, partial_order, verbose, metric, flock_waypoints, band_sample, branch)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/wishbone/core.py", line 262, in _trajectory_landmarks
    paths_l2l.append( [paths[li] for li in l] )
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/wishbone/core.py", line 262, in <listcomp>
    paths_l2l.append( [paths[li] for li in l] )
KeyError: 364

[Count_data.zip](https://github.com/ManuSetty/wishbone/files/1655755/Count_data.zip)

**Comment by ManuSetty** [comment]
Hello

This has been fixed in 96f40895718e39e05df0b7c0e877d0bf7883428d. Please update your repository, reinstall and try again.

Thanks
