### ISSUE TITLE
Install Error: Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/tsne

### ISSUE THREAD

**Issue by inakicm** [ManuSetty/wishbone#6]
Hi,

It might be my fault but I've got an error while trying to install wishbone...

```
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/tsne
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python3/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python3/dist-packages/pip/util.py", line 715, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/tsne
```

Is it because of the "tsne package" or something else?

Thanks,
All the best,

**Comment by ManuSetty** [comment]
This could be a tsne issue. Can you please install v0.1.3 from here https://github.com/danielfrg/tsne/releases. I will update the dependency in a patch release.

**Comment by ManuSetty** [comment]
The package used for running `tSNE` has been updated from `bh_sne` to `bhtsne` and this issue should be resolved.
