### ISSUE TITLE
windows cannot recognize sudo command 

### ISSUE THREAD

**Issue by olivia930709** [ManuSetty/wishbone#64]
Hello,
I'm trying to install wishbone and its dependencies using ' sudo pip3 install . ' following the instruction. However, the prompt says 'sudo is not a external or internal command'. So I may I ask is there any workaround for windows user?

Thanks a lot!
Olivia

**Comment by ManuSetty** [comment]
sudo is specific to Linux / Unix based systems. I believe you should be able to install on Windows without using the sudo: `pip3 install . `. If you see permissions issue, you can try `pip3 install . --user`

**Comment by olivia930709** [comment]
Thank you so much for your reply ! I typed 'pip3 install . ' but it said pip3 is not recognized. So I changed it into 'pip install .' , is that okay?
Anyway, I still got some error at the end, saying files not found. So I'm wondering if there some details I missed, like do I need to change the directory before I type 'git clone git://github.com/manusetty/wishbone.git'?

Many thanks!
Olivia

**Comment by olivia930709** [comment]
Thank you so much for your kind reply! I did exactly as you put in the
README.md. However, here still came some errors as the screenshot shows.
Would you mind take a look and give me some suggestions about it ?

Many thanks!
Olivia

Manu Setty <notifications@github.com> 于2019年1月24日周四 下午1:06写道：

**Comment by ManuSetty** [comment]
The screenshot did not come through. Can you send it again.

**Comment by olivia930709** [comment]
![38e44fc2-a89d-47c6-aebd-831146199b42](https://user-images.githubusercontent.com/36681543/52622098-f1c23000-2ee3-11e9-96ed-268b24ff242b.png)
How about now?

**Comment by ManuSetty** [comment]
Unfortunately, I do not have access to a Windows environment to test this. This looks more an issue with bhtsne_wrapper rather than Wishbone.

**Comment by olivia930709** [comment]
So do you have any suggestions I can at least give it a try?

Many thanks!

**Comment by CyTOF** [comment]
Processing /home/jiaxian/ehbio/wishbone
Collecting Cython (from wishbone==0.4.2)
  Downloading https://files.pythonhosted.org/packages/e7/bd/59054534d09830394470c14e4dd4a2e8fa64ac14559095a044208bf34c18/Cython-0.29.7-cp35-cp35m-manylinux1_x86_64.whl (2.0MB)
    100% |████████████████████████████████| 2.0MB 514kB/s
Collecting bhtsne (from wishbone==0.4.2)
  Downloading https://files.pythonhosted.org/packages/5b/32/3e25093337ab8811e0c3ebd89ad60fd6ca19ef9d7cebb645454f2bc59eaf/bhtsne-0.1.9.tar.gz (86kB)
    100% |████████████████████████████████| 92kB 6.6MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-u1nolrp3/bhtsne/setup.py", line 4, in <module>
        from Cython.Build import cythonize
    ImportError: No module named 'Cython'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-u1nolrp3/bhtsne/

**Comment by ManuSetty** [comment]
Please first try to install Cython using (pip3 install Cython) and then install Wishbone. We will update the dependencies.

**Comment by CyTOF** [comment]
Hi，
    Thank you for your reply.
   I don't understand how to generate the file of "masscyt_waypoint.csv" and what't the meaning?
| |
厦门大学贾贤
|
|
xmujiaxian@163.com
|
签名由网易邮箱大师定制
On 5/7/2019 10:27，Manu Setty<notifications@github.com> wrote：

Please first try to install Cython using (pip3 install Cython) and then install Wishbone. We will update the dependencies.

**Comment by ManuSetty** [comment]
That file is only for the sample data. You don't have to generate that file for your data - you can just specify the number of waypoints (the default option should suffice)
