### ISSUE TITLE
Wishbone failing for non branching trajectories

### ISSUE THREAD

**Issue by ManuSetty** [ManuSetty/wishbone#8]
Wishbone is trying to return branch association scores even when ```branch=False``` and fails with the following error message

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/wishbone/wb.py", line 1046, in run_wishbone
    s=s, k=k, l=k, num_waypoints=num_waypoints, branch=branch)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/wishbone/core.py", line 116, in wishbone
    [trajectory[0], waypoints[0], branches[0], bas[0]]))
IndexError: list index out of range`

**Comment by ManuSetty** [comment]
Fixed in develop. Commit c328208e37c8790486089c615e9000a593ba7e7e
